# prometheus-values.yaml
server:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
alertmanager:
  alertmanagerSpec:
    config:
      route:
        receiver: 'email-receiver'
      receivers:
      - name: 'email-receiver'
        email_configs:
        - to: 'liogrb7@gmail.com'
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 250Mi


serverFiles:
  alerting_rules.yml:
    groups:
    - name: pod-replicas
      rules:
      - alert: PodReplicasLessThanThree
        expr: kube_deployment_status_replicas{namespace="default", deployment="flask-app"} < 3
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod Replicas Less Than Three (instance {{ $labels.instance }})"
          description: "The deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has less than 3 replicas.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

