serverFiles:
  alerting_rules.yml:
    groups:
    - name: pod-replicas
      rules:
      - alert: PodReplicasLessThanThree
        expr: kube_deployment_status_replicas{namespace="default", deployment="deployment.yaml"} < 3
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod Replicas Less Than Three (instance {{ $labels.instance }})"
          description: "The deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has less than 3 replicas.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
alertmanager:
  enabled: true
  alertmanagerSpec:
    config:
      route:
        receiver: 'email-receiver'
      receivers:
      - name: 'email-receiver'
        email_configs:
        - to: 'liogrb7@gmail.com'
